// Copyright 2009 Google Inc.  All Rights Reserved.
// Author: mukai
//
// This file is automatically generated by
// generate_maping.py.
// Do not edit directly and do not include this from any file other
// than KeyCodeMap.mm

namespace {
static map<unichar, KeyEvent::SpecialKey> *kSpecialCharMap = NULL;
static map<unichar, KeyEvent::SpecialKey> *kSpecialCharMapShift = NULL;
static once_t kOnceForSpecialCharMap = MOZC_ONCE_INIT;
void InitSpecialCharMap() {
  if (kSpecialCharMap != NULL || kSpecialCharMapShift != NULL) {
    return;
  }
  kSpecialCharMap = new(nothrow)map<unichar, KeyEvent::SpecialKey>;
  if (kSpecialCharMap == NULL) {
    return;
  }
  kSpecialCharMapShift = new(nothrow)map<unichar, KeyEvent::SpecialKey>;
  if (kSpecialCharMapShift == NULL) {
    delete kSpecialCharMap;
    kSpecialCharMap = NULL;
    return;
  }

  (*kSpecialCharMap)[kBackspaceCharCode] = KeyEvent::BACKSPACE;
  (*kSpecialCharMap)[kEnterCharCode] = KeyEvent::ENTER;
}
}  // anonymous namespace

