// This header file is generated by gen_stats_list.py
const char kConversionWindowDurationMSec[] = "ConversionWindowDurationMSec";
const char kPredictionWindowDurationMSec[] = "PredictionWindowDurationMSec";
const char kSuggestionWindowDurationMSec[] = "SuggestionWindowDurationMSec";
const char kInfolistWindowDurationMSec[] = "InfolistWindowDurationMSec";
const char kCommit[] = "Commit";
const char kCommitFromPrediction[] = "CommitFromPrediction";
const char kCommitFromConversion[] = "CommitFromConversion";
const char kCommitFromComposition[] = "CommitFromComposition";
const char kCommitFromUnknown[] = "CommitFromUnknown";
const char kCommitEmoji[] = "CommitEmoji";
const char kCommitFromConversionInChromeOmnibox[] = "CommitFromConversionInChromeOmnibox";
const char kCommitFromPredictionInChromeOmnibox[] = "CommitFromPredictionInChromeOmnibox";
const char kCommitFromCompositionInChromeOmnibox[] = "CommitFromCompositionInChromeOmnibox";
const char kCommitFromConversionInGoogleSearchBox[] = "CommitFromConversionInGoogleSearchBox";
const char kCommitFromPredictionInGoogleSearchBox[] = "CommitFromPredictionInGoogleSearchBox";
const char kCommitFromCompositionInGoogleSearchBox[] = "CommitFromCompositionInGoogleSearchBox";
const char kCommitPartialSuggestion[] = "CommitPartialSuggestion";
const char kCommitAutoPartialSuggestion[] = "CommitAutoPartialSuggestion";
const char kCommitUnicodeEmoji[] = "CommitUnicodeEmoji";
const char kCommitCarrierEmoji[] = "CommitCarrierEmoji";
const char kSessionAllEvent[] = "SessionAllEvent";
const char kElapsedTimeUSec[] = "ElapsedTimeUSec";
const char kSessionCreated[] = "SessionCreated";
const char kSetConfig[] = "SetConfig";
const char kSubmittedTotalLength[] = "SubmittedTotalLength";
const char kSubmittedSegmentLengthx1000[] = "SubmittedSegmentLengthx1000";
const char kSubmittedSegmentNumberx1000[] = "SubmittedSegmentNumberx1000";
const char kSubmittedLengthx1000[] = "SubmittedLengthx1000";
const char kASCIITyping[] = "ASCIITyping";
const char kNonASCIITyping[] = "NonASCIITyping";
const char kPredictionCandidates0[] = "PredictionCandidates0";
const char kPredictionCandidates1[] = "PredictionCandidates1";
const char kPredictionCandidates2[] = "PredictionCandidates2";
const char kPredictionCandidates3[] = "PredictionCandidates3";
const char kPredictionCandidates4[] = "PredictionCandidates4";
const char kPredictionCandidates5[] = "PredictionCandidates5";
const char kPredictionCandidates6[] = "PredictionCandidates6";
const char kPredictionCandidates7[] = "PredictionCandidates7";
const char kPredictionCandidates8[] = "PredictionCandidates8";
const char kPredictionCandidates9[] = "PredictionCandidates9";
const char kPredictionCandidatesGE10[] = "PredictionCandidatesGE10";
const char kConversionCandidates0[] = "ConversionCandidates0";
const char kConversionCandidates1[] = "ConversionCandidates1";
const char kConversionCandidates2[] = "ConversionCandidates2";
const char kConversionCandidates3[] = "ConversionCandidates3";
const char kConversionCandidates4[] = "ConversionCandidates4";
const char kConversionCandidates5[] = "ConversionCandidates5";
const char kConversionCandidates6[] = "ConversionCandidates6";
const char kConversionCandidates7[] = "ConversionCandidates7";
const char kConversionCandidates8[] = "ConversionCandidates8";
const char kConversionCandidates9[] = "ConversionCandidates9";
const char kConversionCandidatesGE10[] = "ConversionCandidatesGE10";
const char kTransliterationCandidates0[] = "TransliterationCandidates0";
const char kTransliterationCandidates1[] = "TransliterationCandidates1";
const char kTransliterationCandidates2[] = "TransliterationCandidates2";
const char kTransliterationCandidates3[] = "TransliterationCandidates3";
const char kTransliterationCandidates4[] = "TransliterationCandidates4";
const char kTransliterationCandidates5[] = "TransliterationCandidates5";
const char kTransliterationCandidates6[] = "TransliterationCandidates6";
const char kTransliterationCandidates7[] = "TransliterationCandidates7";
const char kTransliterationCandidates8[] = "TransliterationCandidates8";
const char kTransliterationCandidates9[] = "TransliterationCandidates9";
const char kTransliterationCandidatesGE10[] = "TransliterationCandidatesGE10";
const char kLanguageAwareSuggestionTriggered[] = "LanguageAwareSuggestionTriggered";
const char kLanguageAwareSuggestionCommitted[] = "LanguageAwareSuggestionCommitted";
const char kMouseSelect[] = "MouseSelect";
const char kSessionDurationMSec[] = "SessionDurationMSec";
const char kPreeditDurationMSec[] = "PreeditDurationMSec";
const char kShowCascadingWindow[] = "ShowCascadingWindow";
const char kShutDown[] = "ShutDown";
const char kConsumedSendKey[] = "ConsumedSendKey";
const char kUnconsumedSendKey[] = "UnconsumedSendKey";
const char kClearUserHistory[] = "ClearUserHistory";
const char kClearUserPrediction[] = "ClearUserPrediction";
const char kClearUnusedUserPrediction[] = "ClearUnusedUserPrediction";
const char kBackSpaceAfterCommit[] = "BackSpaceAfterCommit";
const char kPerformed_Direct_IMEOn[] = "Performed_Direct_IMEOn";
const char kPerformed_Direct_InputModeHiragana[] = "Performed_Direct_InputModeHiragana";
const char kPerformed_Direct_InputModeFullKatakana[] = "Performed_Direct_InputModeFullKatakana";
const char kPerformed_Direct_InputModeHalfKatakana[] = "Performed_Direct_InputModeHalfKatakana";
const char kPerformed_Direct_InputModeFullAlphanumeric[] = "Performed_Direct_InputModeFullAlphanumeric";
const char kPerformed_Direct_InputModeHalfAlphanumeric[] = "Performed_Direct_InputModeHalfAlphanumeric";
const char kPerformed_Direct_Reconvert[] = "Performed_Direct_Reconvert";
const char kPerformed_Precomposition_IMEOff[] = "Performed_Precomposition_IMEOff";
const char kPerformed_Precomposition_IMEOn[] = "Performed_Precomposition_IMEOn";
const char kPerformed_Precomposition_InsertCharacter[] = "Performed_Precomposition_InsertCharacter";
const char kPerformed_Precomposition_InsertSpace[] = "Performed_Precomposition_InsertSpace";
const char kPerformed_Precomposition_InsertAlternateSpace[] = "Performed_Precomposition_InsertAlternateSpace";
const char kPerformed_Precomposition_InsertHalfSpace[] = "Performed_Precomposition_InsertHalfSpace";
const char kPerformed_Precomposition_InsertFullSpace[] = "Performed_Precomposition_InsertFullSpace";
const char kPerformed_Precomposition_ToggleAlphanumericMode[] = "Performed_Precomposition_ToggleAlphanumericMode";
const char kPerformed_Precomposition_InputModeHiragana[] = "Performed_Precomposition_InputModeHiragana";
const char kPerformed_Precomposition_InputModeFullKatakana[] = "Performed_Precomposition_InputModeFullKatakana";
const char kPerformed_Precomposition_InputModeHalfKatakana[] = "Performed_Precomposition_InputModeHalfKatakana";
const char kPerformed_Precomposition_InputModeFullAlphanumeric[] = "Performed_Precomposition_InputModeFullAlphanumeric";
const char kPerformed_Precomposition_InputModeHalfAlphanumeric[] = "Performed_Precomposition_InputModeHalfAlphanumeric";
const char kPerformed_Precomposition_InputModeSwitchKanaType[] = "Performed_Precomposition_InputModeSwitchKanaType";
const char kPerformed_Precomposition_LaunchConfigDialog[] = "Performed_Precomposition_LaunchConfigDialog";
const char kPerformed_Precomposition_LaunchDictionaryTool[] = "Performed_Precomposition_LaunchDictionaryTool";
const char kPerformed_Precomposition_LaunchWordRegisterDialog[] = "Performed_Precomposition_LaunchWordRegisterDialog";
const char kPerformed_Precomposition_Revert[] = "Performed_Precomposition_Revert";
const char kPerformed_Precomposition_Undo[] = "Performed_Precomposition_Undo";
const char kPerformed_Precomposition_Cancel[] = "Performed_Precomposition_Cancel";
const char kPerformed_Precomposition_CancelAndIMEOff[] = "Performed_Precomposition_CancelAndIMEOff";
const char kPerformed_Precomposition_PredictAndConvert[] = "Performed_Precomposition_PredictAndConvert";
const char kPerformed_Precomposition_CommitFirstSuggestion[] = "Performed_Precomposition_CommitFirstSuggestion";
const char kPerformed_Precomposition_Reconvert[] = "Performed_Precomposition_Reconvert";
const char kPerformed_Composition_IMEOff[] = "Performed_Composition_IMEOff";
const char kPerformed_Composition_IMEOn[] = "Performed_Composition_IMEOn";
const char kPerformed_Composition_InsertCharacter[] = "Performed_Composition_InsertCharacter";
const char kPerformed_Composition_Delete[] = "Performed_Composition_Delete";
const char kPerformed_Composition_Backspace[] = "Performed_Composition_Backspace";
const char kPerformed_Composition_InsertSpace[] = "Performed_Composition_InsertSpace";
const char kPerformed_Composition_InsertAlternateSpace[] = "Performed_Composition_InsertAlternateSpace";
const char kPerformed_Composition_InsertHalfSpace[] = "Performed_Composition_InsertHalfSpace";
const char kPerformed_Composition_InsertFullSpace[] = "Performed_Composition_InsertFullSpace";
const char kPerformed_Composition_Cancel[] = "Performed_Composition_Cancel";
const char kPerformed_Composition_CancelAndIMEOff[] = "Performed_Composition_CancelAndIMEOff";
const char kPerformed_Composition_Undo[] = "Performed_Composition_Undo";
const char kPerformed_Composition_MoveCursorLeft[] = "Performed_Composition_MoveCursorLeft";
const char kPerformed_Composition_MoveCursorRight[] = "Performed_Composition_MoveCursorRight";
const char kPerformed_Composition_MoveCursorToBeginning[] = "Performed_Composition_MoveCursorToBeginning";
const char kPerformed_Composition_MoveCursorToEnd[] = "Performed_Composition_MoveCursorToEnd";
const char kPerformed_Composition_Commit[] = "Performed_Composition_Commit";
const char kPerformed_Composition_CommitFirstSuggestion[] = "Performed_Composition_CommitFirstSuggestion";
const char kPerformed_Composition_Convert[] = "Performed_Composition_Convert";
const char kPerformed_Composition_ConvertWithoutHistory[] = "Performed_Composition_ConvertWithoutHistory";
const char kPerformed_Composition_PredictAndConvert[] = "Performed_Composition_PredictAndConvert";
const char kPerformed_Composition_ConvertToHiragana[] = "Performed_Composition_ConvertToHiragana";
const char kPerformed_Composition_ConvertToFullKatakana[] = "Performed_Composition_ConvertToFullKatakana";
const char kPerformed_Composition_ConvertToHalfKatakana[] = "Performed_Composition_ConvertToHalfKatakana";
const char kPerformed_Composition_ConvertToHalfWidth[] = "Performed_Composition_ConvertToHalfWidth";
const char kPerformed_Composition_ConvertToFullAlphanumeric[] = "Performed_Composition_ConvertToFullAlphanumeric";
const char kPerformed_Composition_ConvertToHalfAlphanumeric[] = "Performed_Composition_ConvertToHalfAlphanumeric";
const char kPerformed_Composition_SwitchKanaType[] = "Performed_Composition_SwitchKanaType";
const char kPerformed_Composition_DisplayAsHiragana[] = "Performed_Composition_DisplayAsHiragana";
const char kPerformed_Composition_DisplayAsFullKatakana[] = "Performed_Composition_DisplayAsFullKatakana";
const char kPerformed_Composition_DisplayAsHalfKatakana[] = "Performed_Composition_DisplayAsHalfKatakana";
const char kPerformed_Composition_DisplayAsHalfWidth[] = "Performed_Composition_DisplayAsHalfWidth";
const char kPerformed_Composition_DisplayAsFullAlphanumeric[] = "Performed_Composition_DisplayAsFullAlphanumeric";
const char kPerformed_Composition_DisplayAsHalfAlphanumeric[] = "Performed_Composition_DisplayAsHalfAlphanumeric";
const char kPerformed_Composition_ToggleAlphanumericMode[] = "Performed_Composition_ToggleAlphanumericMode";
const char kPerformed_Composition_InputModeHiragana[] = "Performed_Composition_InputModeHiragana";
const char kPerformed_Composition_InputModeFullKatakana[] = "Performed_Composition_InputModeFullKatakana";
const char kPerformed_Composition_InputModeHalfKatakana[] = "Performed_Composition_InputModeHalfKatakana";
const char kPerformed_Composition_InputModeFullAlphanumeric[] = "Performed_Composition_InputModeFullAlphanumeric";
const char kPerformed_Composition_InputModeHalfAlphanumeric[] = "Performed_Composition_InputModeHalfAlphanumeric";
const char kPerformed_Conversion_IMEOff[] = "Performed_Conversion_IMEOff";
const char kPerformed_Conversion_IMEOn[] = "Performed_Conversion_IMEOn";
const char kPerformed_Conversion_InsertCharacter[] = "Performed_Conversion_InsertCharacter";
const char kPerformed_Conversion_InsertSpace[] = "Performed_Conversion_InsertSpace";
const char kPerformed_Conversion_InsertAlternateSpace[] = "Performed_Conversion_InsertAlternateSpace";
const char kPerformed_Conversion_InsertHalfSpace[] = "Performed_Conversion_InsertHalfSpace";
const char kPerformed_Conversion_InsertFullSpace[] = "Performed_Conversion_InsertFullSpace";
const char kPerformed_Conversion_Cancel[] = "Performed_Conversion_Cancel";
const char kPerformed_Conversion_CancelAndIMEOff[] = "Performed_Conversion_CancelAndIMEOff";
const char kPerformed_Conversion_Undo[] = "Performed_Conversion_Undo";
const char kPerformed_Conversion_SegmentFocusLeft[] = "Performed_Conversion_SegmentFocusLeft";
const char kPerformed_Conversion_SegmentFocusRight[] = "Performed_Conversion_SegmentFocusRight";
const char kPerformed_Conversion_SegmentFocusFirst[] = "Performed_Conversion_SegmentFocusFirst";
const char kPerformed_Conversion_SegmentFocusLast[] = "Performed_Conversion_SegmentFocusLast";
const char kPerformed_Conversion_SegmentWidthExpand[] = "Performed_Conversion_SegmentWidthExpand";
const char kPerformed_Conversion_SegmentWidthShrink[] = "Performed_Conversion_SegmentWidthShrink";
const char kPerformed_Conversion_ConvertNext[] = "Performed_Conversion_ConvertNext";
const char kPerformed_Conversion_ConvertPrev[] = "Performed_Conversion_ConvertPrev";
const char kPerformed_Conversion_ConvertNextPage[] = "Performed_Conversion_ConvertNextPage";
const char kPerformed_Conversion_ConvertPrevPage[] = "Performed_Conversion_ConvertPrevPage";
const char kPerformed_Conversion_PredictAndConvert[] = "Performed_Conversion_PredictAndConvert";
const char kPerformed_Conversion_Commit[] = "Performed_Conversion_Commit";
const char kPerformed_Conversion_CommitOnlyFirstSegment[] = "Performed_Conversion_CommitOnlyFirstSegment";
const char kPerformed_Conversion_ConvertToHiragana[] = "Performed_Conversion_ConvertToHiragana";
const char kPerformed_Conversion_ConvertToFullKatakana[] = "Performed_Conversion_ConvertToFullKatakana";
const char kPerformed_Conversion_ConvertToHalfKatakana[] = "Performed_Conversion_ConvertToHalfKatakana";
const char kPerformed_Conversion_ConvertToHalfWidth[] = "Performed_Conversion_ConvertToHalfWidth";
const char kPerformed_Conversion_ConvertToFullAlphanumeric[] = "Performed_Conversion_ConvertToFullAlphanumeric";
const char kPerformed_Conversion_ConvertToHalfAlphanumeric[] = "Performed_Conversion_ConvertToHalfAlphanumeric";
const char kPerformed_Conversion_SwitchKanaType[] = "Performed_Conversion_SwitchKanaType";
const char kPerformed_Conversion_ToggleAlphanumericMode[] = "Performed_Conversion_ToggleAlphanumericMode";
const char kPerformed_Conversion_DisplayAsHiragana[] = "Performed_Conversion_DisplayAsHiragana";
const char kPerformed_Conversion_DisplayAsFullKatakana[] = "Performed_Conversion_DisplayAsFullKatakana";
const char kPerformed_Conversion_DisplayAsHalfKatakana[] = "Performed_Conversion_DisplayAsHalfKatakana";
const char kPerformed_Conversion_DisplayAsHalfWidth[] = "Performed_Conversion_DisplayAsHalfWidth";
const char kPerformed_Conversion_DisplayAsFullAlphanumeric[] = "Performed_Conversion_DisplayAsFullAlphanumeric";
const char kPerformed_Conversion_DisplayAsHalfAlphanumeric[] = "Performed_Conversion_DisplayAsHalfAlphanumeric";
const char kPerformed_Conversion_InputModeHiragana[] = "Performed_Conversion_InputModeHiragana";
const char kPerformed_Conversion_InputModeFullKatakana[] = "Performed_Conversion_InputModeFullKatakana";
const char kPerformed_Conversion_InputModeHalfKatakana[] = "Performed_Conversion_InputModeHalfKatakana";
const char kPerformed_Conversion_InputModeFullAlphanumeric[] = "Performed_Conversion_InputModeFullAlphanumeric";
const char kPerformed_Conversion_InputModeHalfAlphanumeric[] = "Performed_Conversion_InputModeHalfAlphanumeric";
const char kPerformed_Conversion_ReportBug[] = "Performed_Conversion_ReportBug";
const char kPerformed_Conversion_DeleteSelectedCandidate[] = "Performed_Conversion_DeleteSelectedCandidate";
const char kSendCommand_Revert[] = "SendCommand_Revert";
const char kSendCommand_Submit[] = "SendCommand_Submit";
const char kSendCommand_SelectCandidate[] = "SendCommand_SelectCandidate";
const char kSendCommand_HighlightCandidate[] = "SendCommand_HighlightCandidate";
const char kSendCommand_SwitchInputMode[] = "SendCommand_SwitchInputMode";
const char kSendCommand_GetStatus[] = "SendCommand_GetStatus";
const char kSendCommand_SubmitCandidate[] = "SendCommand_SubmitCandidate";
const char kSendCommand_ConvertReverse[] = "SendCommand_ConvertReverse";
const char kSendCommand_Undo[] = "SendCommand_Undo";
const char kSendCommand_ResetContext[] = "SendCommand_ResetContext";
const char kSendCommand_MoveCursor[] = "SendCommand_MoveCursor";
const char kSendCommand_SwitchInputFieldType[] = "SendCommand_SwitchInputFieldType";
const char kSendCommand_UsageStatsEvent[] = "SendCommand_UsageStatsEvent";
const char kSendCommand_UndoOrRewind[] = "SendCommand_UndoOrRewind";
const char kSendCommand_ExpandSuggestion[] = "SendCommand_ExpandSuggestion";
const char kSendCommand_SendCaretLocation[] = "SendCommand_SendCaretLocation";
const char kSendCommand_ObsoleteSendLanguageBarCommand[] = "SendCommand_ObsoleteSendLanguageBarCommand";
const char kSendCommand_GetAsyncResult[] = "SendCommand_GetAsyncResult";
const char kSendCommand_CommitRawText[] = "SendCommand_CommitRawText";
const char kSendCommand_ConvertPrevPage[] = "SendCommand_ConvertPrevPage";
const char kSendCommand_ConvertNextPage[] = "SendCommand_ConvertNextPage";
const char kSendCommand_TurnOnIme[] = "SendCommand_TurnOnIme";
const char kSendCommand_TurnOffIme[] = "SendCommand_TurnOffIme";
const char kSendCommand_RevertInChromeOmnibox[] = "SendCommand_RevertInChromeOmnibox";
const char kSendCommand_RevertInGoogleSearchBox[] = "SendCommand_RevertInGoogleSearchBox";
const char kNO_SPECIALKEY[] = "NO_SPECIALKEY";
const char kDIGIT[] = "DIGIT";
const char kON[] = "ON";
const char kOFF[] = "OFF";
const char kSPACE[] = "SPACE";
const char kENTER[] = "ENTER";
const char kLEFT[] = "LEFT";
const char kRIGHT[] = "RIGHT";
const char kUP[] = "UP";
const char kDOWN[] = "DOWN";
const char kESCAPE[] = "ESCAPE";
const char kDEL[] = "DEL";
const char kBACKSPACE[] = "BACKSPACE";
const char kHENKAN[] = "HENKAN";
const char kMUHENKAN[] = "MUHENKAN";
const char kKANA[] = "KANA";
const char kHOME[] = "HOME";
const char kEND[] = "END";
const char kTAB[] = "TAB";
const char kF1[] = "F1";
const char kF2[] = "F2";
const char kF3[] = "F3";
const char kF4[] = "F4";
const char kF5[] = "F5";
const char kF6[] = "F6";
const char kF7[] = "F7";
const char kF8[] = "F8";
const char kF9[] = "F9";
const char kF10[] = "F10";
const char kF11[] = "F11";
const char kF12[] = "F12";
const char kPAGE_UP[] = "PAGE_UP";
const char kPAGE_DOWN[] = "PAGE_DOWN";
const char kINSERT[] = "INSERT";
const char kF13[] = "F13";
const char kF14[] = "F14";
const char kF15[] = "F15";
const char kF16[] = "F16";
const char kF17[] = "F17";
const char kF18[] = "F18";
const char kF19[] = "F19";
const char kF20[] = "F20";
const char kF21[] = "F21";
const char kF22[] = "F22";
const char kF23[] = "F23";
const char kF24[] = "F24";
const char kEISU[] = "EISU";
const char kNUMPAD0[] = "NUMPAD0";
const char kNUMPAD1[] = "NUMPAD1";
const char kNUMPAD2[] = "NUMPAD2";
const char kNUMPAD3[] = "NUMPAD3";
const char kNUMPAD4[] = "NUMPAD4";
const char kNUMPAD5[] = "NUMPAD5";
const char kNUMPAD6[] = "NUMPAD6";
const char kNUMPAD7[] = "NUMPAD7";
const char kNUMPAD8[] = "NUMPAD8";
const char kNUMPAD9[] = "NUMPAD9";
const char kMULTIPLY[] = "MULTIPLY";
const char kADD[] = "ADD";
const char kSEPARATOR[] = "SEPARATOR";
const char kSUBTRACT[] = "SUBTRACT";
const char kDECIMAL[] = "DECIMAL";
const char kDIVIDE[] = "DIVIDE";
const char kEQUALS[] = "EQUALS";
const char kTEXT_INPUT[] = "TEXT_INPUT";
const char kHANKAKU[] = "HANKAKU";
const char kKANJI[] = "KANJI";
const char kKATAKANA[] = "KATAKANA";
const char kCAPS_LOCK[] = "CAPS_LOCK";
const char kUNDEFINED_KEY[] = "UNDEFINED_KEY";
const char kCOMMA[] = "COMMA";
const char kCLEAR[] = "CLEAR";
const char kVIRTUAL_LEFT[] = "VIRTUAL_LEFT";
const char kVIRTUAL_RIGHT[] = "VIRTUAL_RIGHT";
const char kVIRTUAL_ENTER[] = "VIRTUAL_ENTER";
const char kConfigSessionKeymap[] = "ConfigSessionKeymap";
const char kConfigPreeditMethod[] = "ConfigPreeditMethod";
const char kConfigCustomRomanTable[] = "ConfigCustomRomanTable";
const char kConfigPunctuationMethod[] = "ConfigPunctuationMethod";
const char kConfigSymbolMethod[] = "ConfigSymbolMethod";
const char kConfigHistoryLearningLevel[] = "ConfigHistoryLearningLevel";
const char kConfigUseDateConversion[] = "ConfigUseDateConversion";
const char kConfigUseSingleKanjiConversion[] = "ConfigUseSingleKanjiConversion";
const char kConfigUseSymbolConversion[] = "ConfigUseSymbolConversion";
const char kConfigUseNumberConversion[] = "ConfigUseNumberConversion";
const char kConfigUseEmoticonConversion[] = "ConfigUseEmoticonConversion";
const char kConfigUseCalculator[] = "ConfigUseCalculator";
const char kConfigUseT13nConversion[] = "ConfigUseT13nConversion";
const char kConfigUseZipCodeConversion[] = "ConfigUseZipCodeConversion";
const char kConfigUseSpellingCorrection[] = "ConfigUseSpellingCorrection";
const char kConfigUseEmojiConversion[] = "ConfigUseEmojiConversion";
const char kConfigIncognito[] = "ConfigIncognito";
const char kConfigSelectionShortcut[] = "ConfigSelectionShortcut";
const char kConfigUseHistorySuggest[] = "ConfigUseHistorySuggest";
const char kConfigUseDictionarySuggest[] = "ConfigUseDictionarySuggest";
const char kConfigUseRealtimeConversion[] = "ConfigUseRealtimeConversion";
const char kConfigSuggestionsSize[] = "ConfigSuggestionsSize";
const char kConfigUseAutoIMETurnOff[] = "ConfigUseAutoIMETurnOff";
const char kConfigUseCascadingWindow[] = "ConfigUseCascadingWindow";
const char kConfigShiftKeyModeSwitch[] = "ConfigShiftKeyModeSwitch";
const char kConfigNumpadCharacterForm[] = "ConfigNumpadCharacterForm";
const char kConfigUseAutoConversion[] = "ConfigUseAutoConversion";
const char kConfigAutoConversionKey[] = "ConfigAutoConversionKey";
const char kConfigYenSignCharacter[] = "ConfigYenSignCharacter";
const char kConfigUseJapaneseLayout[] = "ConfigUseJapaneseLayout";
const char kConfigSpaceCharacterForm[] = "ConfigSpaceCharacterForm";
const char kConfigAllowCloudHandwriting[] = "ConfigAllowCloudHandwriting";
const char kConfigUseLocalUsageDictionary[] = "ConfigUseLocalUsageDictionary";
const char kPrelauncherEnabled[] = "PrelauncherEnabled";
const char kConfigUseModeIndicator[] = "ConfigUseModeIndicator";
const char kPostInstallShowPageRequired[] = "PostInstallShowPageRequired";
const char kPostInstallLogoffRequired[] = "PostInstallLogoffRequired";
const char kPostInstallNothingRequired[] = "PostInstallNothingRequired";
const char kPostInstallSetDefault[] = "PostInstallSetDefault";
const char kPostInstallNotSetDefault[] = "PostInstallNotSetDefault";
const char kPostInstallOkButton[] = "PostInstallOkButton";
const char kPostInstallLogoffNowButton[] = "PostInstallLogoffNowButton";
const char kPostInstallLogoffLaterButton[] = "PostInstallLogoffLaterButton";
const char kPostInstallRejectButton[] = "PostInstallRejectButton";
const char kIMEActivationKeyCustomized[] = "IMEActivationKeyCustomized";
const char kUserRegisteredWord[] = "UserRegisteredWord";
const char kUserHistoryPredictorEntrySize[] = "UserHistoryPredictorEntrySize";
const char kUserBoundaryHistoryEntrySize[] = "UserBoundaryHistoryEntrySize";
const char kUserSegmentHistoryEntrySize[] = "UserSegmentHistoryEntrySize";
const char kAndroidApiLevel[] = "AndroidApiLevel";
const char kTotalPhysicalMemory[] = "TotalPhysicalMemory";
const char kHandwritingOpen[] = "HandwritingOpen";
const char kHandwritingCommit[] = "HandwritingCommit";
const char kCharacterPaletteOpen[] = "CharacterPaletteOpen";
const char kCharacterPaletteCommit[] = "CharacterPaletteCommit";
const char kSoftwareKeyboardLayoutLandscape[] = "SoftwareKeyboardLayoutLandscape";
const char kSoftwareKeyboardLayoutPortrait[] = "SoftwareKeyboardLayoutPortrait";
const char kWindowsX64[] = "WindowsX64";
const char kMsctfVerMajor[] = "MsctfVerMajor";
const char kMsctfVerMinor[] = "MsctfVerMinor";
const char kMsctfVerBuild[] = "MsctfVerBuild";
const char kMsctfVerRevision[] = "MsctfVerRevision";
const char kCuasEnabled[] = "CuasEnabled";
const char kPerUserInputSettingsEnabled[] = "PerUserInputSettingsEnabled";
const char kVirtualKeyboardStats[] = "VirtualKeyboardStats";
const char kVirtualKeyboardMissStats[] = "VirtualKeyboardMissStats";
const char kBigDictionaryState[] = "BigDictionaryState";
const char kUsageStatsUploadFailed[] = "UsageStatsUploadFailed";
const char *kStatsList[] = {
  kConversionWindowDurationMSec,
  kPredictionWindowDurationMSec,
  kSuggestionWindowDurationMSec,
  kInfolistWindowDurationMSec,
  kCommit,
  kCommitFromPrediction,
  kCommitFromConversion,
  kCommitFromComposition,
  kCommitFromUnknown,
  kCommitEmoji,
  kCommitFromConversionInChromeOmnibox,
  kCommitFromPredictionInChromeOmnibox,
  kCommitFromCompositionInChromeOmnibox,
  kCommitFromConversionInGoogleSearchBox,
  kCommitFromPredictionInGoogleSearchBox,
  kCommitFromCompositionInGoogleSearchBox,
  kCommitPartialSuggestion,
  kCommitAutoPartialSuggestion,
  kCommitUnicodeEmoji,
  kCommitCarrierEmoji,
  kSessionAllEvent,
  kElapsedTimeUSec,
  kSessionCreated,
  kSetConfig,
  kSubmittedTotalLength,
  kSubmittedSegmentLengthx1000,
  kSubmittedSegmentNumberx1000,
  kSubmittedLengthx1000,
  kASCIITyping,
  kNonASCIITyping,
  kPredictionCandidates0,
  kPredictionCandidates1,
  kPredictionCandidates2,
  kPredictionCandidates3,
  kPredictionCandidates4,
  kPredictionCandidates5,
  kPredictionCandidates6,
  kPredictionCandidates7,
  kPredictionCandidates8,
  kPredictionCandidates9,
  kPredictionCandidatesGE10,
  kConversionCandidates0,
  kConversionCandidates1,
  kConversionCandidates2,
  kConversionCandidates3,
  kConversionCandidates4,
  kConversionCandidates5,
  kConversionCandidates6,
  kConversionCandidates7,
  kConversionCandidates8,
  kConversionCandidates9,
  kConversionCandidatesGE10,
  kTransliterationCandidates0,
  kTransliterationCandidates1,
  kTransliterationCandidates2,
  kTransliterationCandidates3,
  kTransliterationCandidates4,
  kTransliterationCandidates5,
  kTransliterationCandidates6,
  kTransliterationCandidates7,
  kTransliterationCandidates8,
  kTransliterationCandidates9,
  kTransliterationCandidatesGE10,
  kLanguageAwareSuggestionTriggered,
  kLanguageAwareSuggestionCommitted,
  kMouseSelect,
  kSessionDurationMSec,
  kPreeditDurationMSec,
  kShowCascadingWindow,
  kShutDown,
  kConsumedSendKey,
  kUnconsumedSendKey,
  kClearUserHistory,
  kClearUserPrediction,
  kClearUnusedUserPrediction,
  kBackSpaceAfterCommit,
  kPerformed_Direct_IMEOn,
  kPerformed_Direct_InputModeHiragana,
  kPerformed_Direct_InputModeFullKatakana,
  kPerformed_Direct_InputModeHalfKatakana,
  kPerformed_Direct_InputModeFullAlphanumeric,
  kPerformed_Direct_InputModeHalfAlphanumeric,
  kPerformed_Direct_Reconvert,
  kPerformed_Precomposition_IMEOff,
  kPerformed_Precomposition_IMEOn,
  kPerformed_Precomposition_InsertCharacter,
  kPerformed_Precomposition_InsertSpace,
  kPerformed_Precomposition_InsertAlternateSpace,
  kPerformed_Precomposition_InsertHalfSpace,
  kPerformed_Precomposition_InsertFullSpace,
  kPerformed_Precomposition_ToggleAlphanumericMode,
  kPerformed_Precomposition_InputModeHiragana,
  kPerformed_Precomposition_InputModeFullKatakana,
  kPerformed_Precomposition_InputModeHalfKatakana,
  kPerformed_Precomposition_InputModeFullAlphanumeric,
  kPerformed_Precomposition_InputModeHalfAlphanumeric,
  kPerformed_Precomposition_InputModeSwitchKanaType,
  kPerformed_Precomposition_LaunchConfigDialog,
  kPerformed_Precomposition_LaunchDictionaryTool,
  kPerformed_Precomposition_LaunchWordRegisterDialog,
  kPerformed_Precomposition_Revert,
  kPerformed_Precomposition_Undo,
  kPerformed_Precomposition_Cancel,
  kPerformed_Precomposition_CancelAndIMEOff,
  kPerformed_Precomposition_PredictAndConvert,
  kPerformed_Precomposition_CommitFirstSuggestion,
  kPerformed_Precomposition_Reconvert,
  kPerformed_Composition_IMEOff,
  kPerformed_Composition_IMEOn,
  kPerformed_Composition_InsertCharacter,
  kPerformed_Composition_Delete,
  kPerformed_Composition_Backspace,
  kPerformed_Composition_InsertSpace,
  kPerformed_Composition_InsertAlternateSpace,
  kPerformed_Composition_InsertHalfSpace,
  kPerformed_Composition_InsertFullSpace,
  kPerformed_Composition_Cancel,
  kPerformed_Composition_CancelAndIMEOff,
  kPerformed_Composition_Undo,
  kPerformed_Composition_MoveCursorLeft,
  kPerformed_Composition_MoveCursorRight,
  kPerformed_Composition_MoveCursorToBeginning,
  kPerformed_Composition_MoveCursorToEnd,
  kPerformed_Composition_Commit,
  kPerformed_Composition_CommitFirstSuggestion,
  kPerformed_Composition_Convert,
  kPerformed_Composition_ConvertWithoutHistory,
  kPerformed_Composition_PredictAndConvert,
  kPerformed_Composition_ConvertToHiragana,
  kPerformed_Composition_ConvertToFullKatakana,
  kPerformed_Composition_ConvertToHalfKatakana,
  kPerformed_Composition_ConvertToHalfWidth,
  kPerformed_Composition_ConvertToFullAlphanumeric,
  kPerformed_Composition_ConvertToHalfAlphanumeric,
  kPerformed_Composition_SwitchKanaType,
  kPerformed_Composition_DisplayAsHiragana,
  kPerformed_Composition_DisplayAsFullKatakana,
  kPerformed_Composition_DisplayAsHalfKatakana,
  kPerformed_Composition_DisplayAsHalfWidth,
  kPerformed_Composition_DisplayAsFullAlphanumeric,
  kPerformed_Composition_DisplayAsHalfAlphanumeric,
  kPerformed_Composition_ToggleAlphanumericMode,
  kPerformed_Composition_InputModeHiragana,
  kPerformed_Composition_InputModeFullKatakana,
  kPerformed_Composition_InputModeHalfKatakana,
  kPerformed_Composition_InputModeFullAlphanumeric,
  kPerformed_Composition_InputModeHalfAlphanumeric,
  kPerformed_Conversion_IMEOff,
  kPerformed_Conversion_IMEOn,
  kPerformed_Conversion_InsertCharacter,
  kPerformed_Conversion_InsertSpace,
  kPerformed_Conversion_InsertAlternateSpace,
  kPerformed_Conversion_InsertHalfSpace,
  kPerformed_Conversion_InsertFullSpace,
  kPerformed_Conversion_Cancel,
  kPerformed_Conversion_CancelAndIMEOff,
  kPerformed_Conversion_Undo,
  kPerformed_Conversion_SegmentFocusLeft,
  kPerformed_Conversion_SegmentFocusRight,
  kPerformed_Conversion_SegmentFocusFirst,
  kPerformed_Conversion_SegmentFocusLast,
  kPerformed_Conversion_SegmentWidthExpand,
  kPerformed_Conversion_SegmentWidthShrink,
  kPerformed_Conversion_ConvertNext,
  kPerformed_Conversion_ConvertPrev,
  kPerformed_Conversion_ConvertNextPage,
  kPerformed_Conversion_ConvertPrevPage,
  kPerformed_Conversion_PredictAndConvert,
  kPerformed_Conversion_Commit,
  kPerformed_Conversion_CommitOnlyFirstSegment,
  kPerformed_Conversion_ConvertToHiragana,
  kPerformed_Conversion_ConvertToFullKatakana,
  kPerformed_Conversion_ConvertToHalfKatakana,
  kPerformed_Conversion_ConvertToHalfWidth,
  kPerformed_Conversion_ConvertToFullAlphanumeric,
  kPerformed_Conversion_ConvertToHalfAlphanumeric,
  kPerformed_Conversion_SwitchKanaType,
  kPerformed_Conversion_ToggleAlphanumericMode,
  kPerformed_Conversion_DisplayAsHiragana,
  kPerformed_Conversion_DisplayAsFullKatakana,
  kPerformed_Conversion_DisplayAsHalfKatakana,
  kPerformed_Conversion_DisplayAsHalfWidth,
  kPerformed_Conversion_DisplayAsFullAlphanumeric,
  kPerformed_Conversion_DisplayAsHalfAlphanumeric,
  kPerformed_Conversion_InputModeHiragana,
  kPerformed_Conversion_InputModeFullKatakana,
  kPerformed_Conversion_InputModeHalfKatakana,
  kPerformed_Conversion_InputModeFullAlphanumeric,
  kPerformed_Conversion_InputModeHalfAlphanumeric,
  kPerformed_Conversion_ReportBug,
  kPerformed_Conversion_DeleteSelectedCandidate,
  kSendCommand_Revert,
  kSendCommand_Submit,
  kSendCommand_SelectCandidate,
  kSendCommand_HighlightCandidate,
  kSendCommand_SwitchInputMode,
  kSendCommand_GetStatus,
  kSendCommand_SubmitCandidate,
  kSendCommand_ConvertReverse,
  kSendCommand_Undo,
  kSendCommand_ResetContext,
  kSendCommand_MoveCursor,
  kSendCommand_SwitchInputFieldType,
  kSendCommand_UsageStatsEvent,
  kSendCommand_UndoOrRewind,
  kSendCommand_ExpandSuggestion,
  kSendCommand_SendCaretLocation,
  kSendCommand_ObsoleteSendLanguageBarCommand,
  kSendCommand_GetAsyncResult,
  kSendCommand_CommitRawText,
  kSendCommand_ConvertPrevPage,
  kSendCommand_ConvertNextPage,
  kSendCommand_TurnOnIme,
  kSendCommand_TurnOffIme,
  kSendCommand_RevertInChromeOmnibox,
  kSendCommand_RevertInGoogleSearchBox,
  kNO_SPECIALKEY,
  kDIGIT,
  kON,
  kOFF,
  kSPACE,
  kENTER,
  kLEFT,
  kRIGHT,
  kUP,
  kDOWN,
  kESCAPE,
  kDEL,
  kBACKSPACE,
  kHENKAN,
  kMUHENKAN,
  kKANA,
  kHOME,
  kEND,
  kTAB,
  kF1,
  kF2,
  kF3,
  kF4,
  kF5,
  kF6,
  kF7,
  kF8,
  kF9,
  kF10,
  kF11,
  kF12,
  kPAGE_UP,
  kPAGE_DOWN,
  kINSERT,
  kF13,
  kF14,
  kF15,
  kF16,
  kF17,
  kF18,
  kF19,
  kF20,
  kF21,
  kF22,
  kF23,
  kF24,
  kEISU,
  kNUMPAD0,
  kNUMPAD1,
  kNUMPAD2,
  kNUMPAD3,
  kNUMPAD4,
  kNUMPAD5,
  kNUMPAD6,
  kNUMPAD7,
  kNUMPAD8,
  kNUMPAD9,
  kMULTIPLY,
  kADD,
  kSEPARATOR,
  kSUBTRACT,
  kDECIMAL,
  kDIVIDE,
  kEQUALS,
  kTEXT_INPUT,
  kHANKAKU,
  kKANJI,
  kKATAKANA,
  kCAPS_LOCK,
  kUNDEFINED_KEY,
  kCOMMA,
  kCLEAR,
  kVIRTUAL_LEFT,
  kVIRTUAL_RIGHT,
  kVIRTUAL_ENTER,
  kConfigSessionKeymap,
  kConfigPreeditMethod,
  kConfigCustomRomanTable,
  kConfigPunctuationMethod,
  kConfigSymbolMethod,
  kConfigHistoryLearningLevel,
  kConfigUseDateConversion,
  kConfigUseSingleKanjiConversion,
  kConfigUseSymbolConversion,
  kConfigUseNumberConversion,
  kConfigUseEmoticonConversion,
  kConfigUseCalculator,
  kConfigUseT13nConversion,
  kConfigUseZipCodeConversion,
  kConfigUseSpellingCorrection,
  kConfigUseEmojiConversion,
  kConfigIncognito,
  kConfigSelectionShortcut,
  kConfigUseHistorySuggest,
  kConfigUseDictionarySuggest,
  kConfigUseRealtimeConversion,
  kConfigSuggestionsSize,
  kConfigUseAutoIMETurnOff,
  kConfigUseCascadingWindow,
  kConfigShiftKeyModeSwitch,
  kConfigNumpadCharacterForm,
  kConfigUseAutoConversion,
  kConfigAutoConversionKey,
  kConfigYenSignCharacter,
  kConfigUseJapaneseLayout,
  kConfigSpaceCharacterForm,
  kConfigAllowCloudHandwriting,
  kConfigUseLocalUsageDictionary,
  kPrelauncherEnabled,
  kConfigUseModeIndicator,
  kPostInstallShowPageRequired,
  kPostInstallLogoffRequired,
  kPostInstallNothingRequired,
  kPostInstallSetDefault,
  kPostInstallNotSetDefault,
  kPostInstallOkButton,
  kPostInstallLogoffNowButton,
  kPostInstallLogoffLaterButton,
  kPostInstallRejectButton,
  kIMEActivationKeyCustomized,
  kUserRegisteredWord,
  kUserHistoryPredictorEntrySize,
  kUserBoundaryHistoryEntrySize,
  kUserSegmentHistoryEntrySize,
  kAndroidApiLevel,
  kTotalPhysicalMemory,
  kHandwritingOpen,
  kHandwritingCommit,
  kCharacterPaletteOpen,
  kCharacterPaletteCommit,
  kSoftwareKeyboardLayoutLandscape,
  kSoftwareKeyboardLayoutPortrait,
  kWindowsX64,
  kMsctfVerMajor,
  kMsctfVerMinor,
  kMsctfVerBuild,
  kMsctfVerRevision,
  kCuasEnabled,
  kPerUserInputSettingsEnabled,
  kVirtualKeyboardStats,
  kVirtualKeyboardMissStats,
  kBigDictionaryState,
  kUsageStatsUploadFailed,
};
