// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: usage_stats/usage_stats.proto

#ifndef PROTOBUF_usage_5fstats_2fusage_5fstats_2eproto__INCLUDED
#define PROTOBUF_usage_5fstats_2fusage_5fstats_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace mozc {
namespace usage_stats {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_usage_5fstats_2fusage_5fstats_2eproto();
void protobuf_AssignDesc_usage_5fstats_2fusage_5fstats_2eproto();
void protobuf_ShutdownFile_usage_5fstats_2fusage_5fstats_2eproto();

class Stats;
class Stats_DoubleValueStats;
class Stats_TouchEventStats;
class Stats_VirtualKeyboardStats;

enum Stats_Type {
  Stats_Type_COUNT = 0,
  Stats_Type_TIMING = 1,
  Stats_Type_INTEGER = 2,
  Stats_Type_BOOLEAN = 3,
  Stats_Type_VIRTUAL_KEYBOARD = 4
};
bool Stats_Type_IsValid(int value);
const Stats_Type Stats_Type_Type_MIN = Stats_Type_COUNT;
const Stats_Type Stats_Type_Type_MAX = Stats_Type_VIRTUAL_KEYBOARD;
const int Stats_Type_Type_ARRAYSIZE = Stats_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Stats_Type_descriptor();
inline const ::std::string& Stats_Type_Name(Stats_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Stats_Type_descriptor(), value);
}
inline bool Stats_Type_Parse(
    const ::std::string& name, Stats_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Stats_Type>(
    Stats_Type_descriptor(), name, value);
}
// ===================================================================

class Stats_DoubleValueStats : public ::google::protobuf::Message {
 public:
  Stats_DoubleValueStats();
  virtual ~Stats_DoubleValueStats();

  Stats_DoubleValueStats(const Stats_DoubleValueStats& from);

  inline Stats_DoubleValueStats& operator=(const Stats_DoubleValueStats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stats_DoubleValueStats& default_instance();

  void Swap(Stats_DoubleValueStats* other);

  // implements Message ----------------------------------------------

  Stats_DoubleValueStats* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stats_DoubleValueStats& from);
  void MergeFrom(const Stats_DoubleValueStats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 num = 1;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 1;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // optional double total = 2;
  inline bool has_total() const;
  inline void clear_total();
  static const int kTotalFieldNumber = 2;
  inline double total() const;
  inline void set_total(double value);

  // optional double square_total = 3;
  inline bool has_square_total() const;
  inline void clear_square_total();
  static const int kSquareTotalFieldNumber = 3;
  inline double square_total() const;
  inline void set_square_total(double value);

  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats.DoubleValueStats)
 private:
  inline void set_has_num();
  inline void clear_has_num();
  inline void set_has_total();
  inline void clear_has_total();
  inline void set_has_square_total();
  inline void clear_has_square_total();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  double total_;
  double square_total_;
  ::google::protobuf::uint32 num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_AssignDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_ShutdownFile_usage_5fstats_2fusage_5fstats_2eproto();

  void InitAsDefaultInstance();
  static Stats_DoubleValueStats* default_instance_;
};
// -------------------------------------------------------------------

class Stats_TouchEventStats : public ::google::protobuf::Message {
 public:
  Stats_TouchEventStats();
  virtual ~Stats_TouchEventStats();

  Stats_TouchEventStats(const Stats_TouchEventStats& from);

  inline Stats_TouchEventStats& operator=(const Stats_TouchEventStats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stats_TouchEventStats& default_instance();

  void Swap(Stats_TouchEventStats* other);

  // implements Message ----------------------------------------------

  Stats_TouchEventStats* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stats_TouchEventStats& from);
  void MergeFrom(const Stats_TouchEventStats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 source_id = 1;
  inline bool has_source_id() const;
  inline void clear_source_id();
  static const int kSourceIdFieldNumber = 1;
  inline ::google::protobuf::uint32 source_id() const;
  inline void set_source_id(::google::protobuf::uint32 value);

  // optional .mozc.usage_stats.Stats.DoubleValueStats start_x_stats = 2;
  inline bool has_start_x_stats() const;
  inline void clear_start_x_stats();
  static const int kStartXStatsFieldNumber = 2;
  inline const ::mozc::usage_stats::Stats_DoubleValueStats& start_x_stats() const;
  inline ::mozc::usage_stats::Stats_DoubleValueStats* mutable_start_x_stats();
  inline ::mozc::usage_stats::Stats_DoubleValueStats* release_start_x_stats();
  inline void set_allocated_start_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* start_x_stats);

  // optional .mozc.usage_stats.Stats.DoubleValueStats start_y_stats = 3;
  inline bool has_start_y_stats() const;
  inline void clear_start_y_stats();
  static const int kStartYStatsFieldNumber = 3;
  inline const ::mozc::usage_stats::Stats_DoubleValueStats& start_y_stats() const;
  inline ::mozc::usage_stats::Stats_DoubleValueStats* mutable_start_y_stats();
  inline ::mozc::usage_stats::Stats_DoubleValueStats* release_start_y_stats();
  inline void set_allocated_start_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* start_y_stats);

  // optional .mozc.usage_stats.Stats.DoubleValueStats direction_x_stats = 4;
  inline bool has_direction_x_stats() const;
  inline void clear_direction_x_stats();
  static const int kDirectionXStatsFieldNumber = 4;
  inline const ::mozc::usage_stats::Stats_DoubleValueStats& direction_x_stats() const;
  inline ::mozc::usage_stats::Stats_DoubleValueStats* mutable_direction_x_stats();
  inline ::mozc::usage_stats::Stats_DoubleValueStats* release_direction_x_stats();
  inline void set_allocated_direction_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* direction_x_stats);

  // optional .mozc.usage_stats.Stats.DoubleValueStats direction_y_stats = 5;
  inline bool has_direction_y_stats() const;
  inline void clear_direction_y_stats();
  static const int kDirectionYStatsFieldNumber = 5;
  inline const ::mozc::usage_stats::Stats_DoubleValueStats& direction_y_stats() const;
  inline ::mozc::usage_stats::Stats_DoubleValueStats* mutable_direction_y_stats();
  inline ::mozc::usage_stats::Stats_DoubleValueStats* release_direction_y_stats();
  inline void set_allocated_direction_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* direction_y_stats);

  // optional .mozc.usage_stats.Stats.DoubleValueStats time_length_stats = 6;
  inline bool has_time_length_stats() const;
  inline void clear_time_length_stats();
  static const int kTimeLengthStatsFieldNumber = 6;
  inline const ::mozc::usage_stats::Stats_DoubleValueStats& time_length_stats() const;
  inline ::mozc::usage_stats::Stats_DoubleValueStats* mutable_time_length_stats();
  inline ::mozc::usage_stats::Stats_DoubleValueStats* release_time_length_stats();
  inline void set_allocated_time_length_stats(::mozc::usage_stats::Stats_DoubleValueStats* time_length_stats);

  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats.TouchEventStats)
 private:
  inline void set_has_source_id();
  inline void clear_has_source_id();
  inline void set_has_start_x_stats();
  inline void clear_has_start_x_stats();
  inline void set_has_start_y_stats();
  inline void clear_has_start_y_stats();
  inline void set_has_direction_x_stats();
  inline void clear_has_direction_x_stats();
  inline void set_has_direction_y_stats();
  inline void clear_has_direction_y_stats();
  inline void set_has_time_length_stats();
  inline void clear_has_time_length_stats();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::mozc::usage_stats::Stats_DoubleValueStats* start_x_stats_;
  ::mozc::usage_stats::Stats_DoubleValueStats* start_y_stats_;
  ::mozc::usage_stats::Stats_DoubleValueStats* direction_x_stats_;
  ::mozc::usage_stats::Stats_DoubleValueStats* direction_y_stats_;
  ::mozc::usage_stats::Stats_DoubleValueStats* time_length_stats_;
  ::google::protobuf::uint32 source_id_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];

  friend void  protobuf_AddDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_AssignDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_ShutdownFile_usage_5fstats_2fusage_5fstats_2eproto();

  void InitAsDefaultInstance();
  static Stats_TouchEventStats* default_instance_;
};
// -------------------------------------------------------------------

class Stats_VirtualKeyboardStats : public ::google::protobuf::Message {
 public:
  Stats_VirtualKeyboardStats();
  virtual ~Stats_VirtualKeyboardStats();

  Stats_VirtualKeyboardStats(const Stats_VirtualKeyboardStats& from);

  inline Stats_VirtualKeyboardStats& operator=(const Stats_VirtualKeyboardStats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stats_VirtualKeyboardStats& default_instance();

  void Swap(Stats_VirtualKeyboardStats* other);

  // implements Message ----------------------------------------------

  Stats_VirtualKeyboardStats* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stats_VirtualKeyboardStats& from);
  void MergeFrom(const Stats_VirtualKeyboardStats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string keyboard_name = 1;
  inline bool has_keyboard_name() const;
  inline void clear_keyboard_name();
  static const int kKeyboardNameFieldNumber = 1;
  inline const ::std::string& keyboard_name() const;
  inline void set_keyboard_name(const ::std::string& value);
  inline void set_keyboard_name(const char* value);
  inline void set_keyboard_name(const char* value, size_t size);
  inline ::std::string* mutable_keyboard_name();
  inline ::std::string* release_keyboard_name();
  inline void set_allocated_keyboard_name(::std::string* keyboard_name);

  // repeated .mozc.usage_stats.Stats.TouchEventStats touch_event_stats = 2;
  inline int touch_event_stats_size() const;
  inline void clear_touch_event_stats();
  static const int kTouchEventStatsFieldNumber = 2;
  inline const ::mozc::usage_stats::Stats_TouchEventStats& touch_event_stats(int index) const;
  inline ::mozc::usage_stats::Stats_TouchEventStats* mutable_touch_event_stats(int index);
  inline ::mozc::usage_stats::Stats_TouchEventStats* add_touch_event_stats();
  inline const ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_TouchEventStats >&
      touch_event_stats() const;
  inline ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_TouchEventStats >*
      mutable_touch_event_stats();

  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats.VirtualKeyboardStats)
 private:
  inline void set_has_keyboard_name();
  inline void clear_has_keyboard_name();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* keyboard_name_;
  ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_TouchEventStats > touch_event_stats_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_AssignDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_ShutdownFile_usage_5fstats_2fusage_5fstats_2eproto();

  void InitAsDefaultInstance();
  static Stats_VirtualKeyboardStats* default_instance_;
};
// -------------------------------------------------------------------

class Stats : public ::google::protobuf::Message {
 public:
  Stats();
  virtual ~Stats();

  Stats(const Stats& from);

  inline Stats& operator=(const Stats& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Stats& default_instance();

  void Swap(Stats* other);

  // implements Message ----------------------------------------------

  Stats* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Stats& from);
  void MergeFrom(const Stats& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Stats_DoubleValueStats DoubleValueStats;
  typedef Stats_TouchEventStats TouchEventStats;
  typedef Stats_VirtualKeyboardStats VirtualKeyboardStats;

  typedef Stats_Type Type;
  static const Type COUNT = Stats_Type_COUNT;
  static const Type TIMING = Stats_Type_TIMING;
  static const Type INTEGER = Stats_Type_INTEGER;
  static const Type BOOLEAN = Stats_Type_BOOLEAN;
  static const Type VIRTUAL_KEYBOARD = Stats_Type_VIRTUAL_KEYBOARD;
  static inline bool Type_IsValid(int value) {
    return Stats_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Stats_Type_Type_MIN;
  static const Type Type_MAX =
    Stats_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Stats_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Stats_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Stats_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Stats_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // required .mozc.usage_stats.Stats.Type type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::mozc::usage_stats::Stats_Type type() const;
  inline void set_type(::mozc::usage_stats::Stats_Type value);

  // optional uint32 count = 3;
  inline bool has_count() const;
  inline void clear_count();
  static const int kCountFieldNumber = 3;
  inline ::google::protobuf::uint32 count() const;
  inline void set_count(::google::protobuf::uint32 value);

  // optional uint64 total_time = 10;
  inline bool has_total_time() const;
  inline void clear_total_time();
  static const int kTotalTimeFieldNumber = 10;
  inline ::google::protobuf::uint64 total_time() const;
  inline void set_total_time(::google::protobuf::uint64 value);

  // optional uint32 num_timings = 4;
  inline bool has_num_timings() const;
  inline void clear_num_timings();
  static const int kNumTimingsFieldNumber = 4;
  inline ::google::protobuf::uint32 num_timings() const;
  inline void set_num_timings(::google::protobuf::uint32 value);

  // optional uint32 avg_time = 5;
  inline bool has_avg_time() const;
  inline void clear_avg_time();
  static const int kAvgTimeFieldNumber = 5;
  inline ::google::protobuf::uint32 avg_time() const;
  inline void set_avg_time(::google::protobuf::uint32 value);

  // optional uint32 min_time = 6;
  inline bool has_min_time() const;
  inline void clear_min_time();
  static const int kMinTimeFieldNumber = 6;
  inline ::google::protobuf::uint32 min_time() const;
  inline void set_min_time(::google::protobuf::uint32 value);

  // optional uint32 max_time = 7;
  inline bool has_max_time() const;
  inline void clear_max_time();
  static const int kMaxTimeFieldNumber = 7;
  inline ::google::protobuf::uint32 max_time() const;
  inline void set_max_time(::google::protobuf::uint32 value);

  // optional int32 int_value = 8;
  inline bool has_int_value() const;
  inline void clear_int_value();
  static const int kIntValueFieldNumber = 8;
  inline ::google::protobuf::int32 int_value() const;
  inline void set_int_value(::google::protobuf::int32 value);

  // optional bool boolean_value = 9;
  inline bool has_boolean_value() const;
  inline void clear_boolean_value();
  static const int kBooleanValueFieldNumber = 9;
  inline bool boolean_value() const;
  inline void set_boolean_value(bool value);

  // repeated .mozc.usage_stats.Stats.VirtualKeyboardStats virtual_keyboard_stats = 11;
  inline int virtual_keyboard_stats_size() const;
  inline void clear_virtual_keyboard_stats();
  static const int kVirtualKeyboardStatsFieldNumber = 11;
  inline const ::mozc::usage_stats::Stats_VirtualKeyboardStats& virtual_keyboard_stats(int index) const;
  inline ::mozc::usage_stats::Stats_VirtualKeyboardStats* mutable_virtual_keyboard_stats(int index);
  inline ::mozc::usage_stats::Stats_VirtualKeyboardStats* add_virtual_keyboard_stats();
  inline const ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_VirtualKeyboardStats >&
      virtual_keyboard_stats() const;
  inline ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_VirtualKeyboardStats >*
      mutable_virtual_keyboard_stats();

  // @@protoc_insertion_point(class_scope:mozc.usage_stats.Stats)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_count();
  inline void clear_has_count();
  inline void set_has_total_time();
  inline void clear_has_total_time();
  inline void set_has_num_timings();
  inline void clear_has_num_timings();
  inline void set_has_avg_time();
  inline void clear_has_avg_time();
  inline void set_has_min_time();
  inline void clear_has_min_time();
  inline void set_has_max_time();
  inline void clear_has_max_time();
  inline void set_has_int_value();
  inline void clear_has_int_value();
  inline void set_has_boolean_value();
  inline void clear_has_boolean_value();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  int type_;
  ::google::protobuf::uint32 count_;
  ::google::protobuf::uint64 total_time_;
  ::google::protobuf::uint32 num_timings_;
  ::google::protobuf::uint32 avg_time_;
  ::google::protobuf::uint32 min_time_;
  ::google::protobuf::uint32 max_time_;
  ::google::protobuf::int32 int_value_;
  bool boolean_value_;
  ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_VirtualKeyboardStats > virtual_keyboard_stats_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(11 + 31) / 32];

  friend void  protobuf_AddDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_AssignDesc_usage_5fstats_2fusage_5fstats_2eproto();
  friend void protobuf_ShutdownFile_usage_5fstats_2fusage_5fstats_2eproto();

  void InitAsDefaultInstance();
  static Stats* default_instance_;
};
// ===================================================================


// ===================================================================

// Stats_DoubleValueStats

// optional uint32 num = 1;
inline bool Stats_DoubleValueStats::has_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stats_DoubleValueStats::set_has_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stats_DoubleValueStats::clear_has_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stats_DoubleValueStats::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 Stats_DoubleValueStats::num() const {
  return num_;
}
inline void Stats_DoubleValueStats::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
}

// optional double total = 2;
inline bool Stats_DoubleValueStats::has_total() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Stats_DoubleValueStats::set_has_total() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Stats_DoubleValueStats::clear_has_total() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Stats_DoubleValueStats::clear_total() {
  total_ = 0;
  clear_has_total();
}
inline double Stats_DoubleValueStats::total() const {
  return total_;
}
inline void Stats_DoubleValueStats::set_total(double value) {
  set_has_total();
  total_ = value;
}

// optional double square_total = 3;
inline bool Stats_DoubleValueStats::has_square_total() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Stats_DoubleValueStats::set_has_square_total() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Stats_DoubleValueStats::clear_has_square_total() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Stats_DoubleValueStats::clear_square_total() {
  square_total_ = 0;
  clear_has_square_total();
}
inline double Stats_DoubleValueStats::square_total() const {
  return square_total_;
}
inline void Stats_DoubleValueStats::set_square_total(double value) {
  set_has_square_total();
  square_total_ = value;
}

// -------------------------------------------------------------------

// Stats_TouchEventStats

// optional uint32 source_id = 1;
inline bool Stats_TouchEventStats::has_source_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stats_TouchEventStats::set_has_source_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stats_TouchEventStats::clear_has_source_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stats_TouchEventStats::clear_source_id() {
  source_id_ = 0u;
  clear_has_source_id();
}
inline ::google::protobuf::uint32 Stats_TouchEventStats::source_id() const {
  return source_id_;
}
inline void Stats_TouchEventStats::set_source_id(::google::protobuf::uint32 value) {
  set_has_source_id();
  source_id_ = value;
}

// optional .mozc.usage_stats.Stats.DoubleValueStats start_x_stats = 2;
inline bool Stats_TouchEventStats::has_start_x_stats() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Stats_TouchEventStats::set_has_start_x_stats() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Stats_TouchEventStats::clear_has_start_x_stats() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Stats_TouchEventStats::clear_start_x_stats() {
  if (start_x_stats_ != NULL) start_x_stats_->::mozc::usage_stats::Stats_DoubleValueStats::Clear();
  clear_has_start_x_stats();
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::start_x_stats() const {
  return start_x_stats_ != NULL ? *start_x_stats_ : *default_instance_->start_x_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_start_x_stats() {
  set_has_start_x_stats();
  if (start_x_stats_ == NULL) start_x_stats_ = new ::mozc::usage_stats::Stats_DoubleValueStats;
  return start_x_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_start_x_stats() {
  clear_has_start_x_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = start_x_stats_;
  start_x_stats_ = NULL;
  return temp;
}
inline void Stats_TouchEventStats::set_allocated_start_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* start_x_stats) {
  delete start_x_stats_;
  start_x_stats_ = start_x_stats;
  if (start_x_stats) {
    set_has_start_x_stats();
  } else {
    clear_has_start_x_stats();
  }
}

// optional .mozc.usage_stats.Stats.DoubleValueStats start_y_stats = 3;
inline bool Stats_TouchEventStats::has_start_y_stats() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Stats_TouchEventStats::set_has_start_y_stats() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Stats_TouchEventStats::clear_has_start_y_stats() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Stats_TouchEventStats::clear_start_y_stats() {
  if (start_y_stats_ != NULL) start_y_stats_->::mozc::usage_stats::Stats_DoubleValueStats::Clear();
  clear_has_start_y_stats();
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::start_y_stats() const {
  return start_y_stats_ != NULL ? *start_y_stats_ : *default_instance_->start_y_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_start_y_stats() {
  set_has_start_y_stats();
  if (start_y_stats_ == NULL) start_y_stats_ = new ::mozc::usage_stats::Stats_DoubleValueStats;
  return start_y_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_start_y_stats() {
  clear_has_start_y_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = start_y_stats_;
  start_y_stats_ = NULL;
  return temp;
}
inline void Stats_TouchEventStats::set_allocated_start_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* start_y_stats) {
  delete start_y_stats_;
  start_y_stats_ = start_y_stats;
  if (start_y_stats) {
    set_has_start_y_stats();
  } else {
    clear_has_start_y_stats();
  }
}

// optional .mozc.usage_stats.Stats.DoubleValueStats direction_x_stats = 4;
inline bool Stats_TouchEventStats::has_direction_x_stats() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Stats_TouchEventStats::set_has_direction_x_stats() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Stats_TouchEventStats::clear_has_direction_x_stats() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Stats_TouchEventStats::clear_direction_x_stats() {
  if (direction_x_stats_ != NULL) direction_x_stats_->::mozc::usage_stats::Stats_DoubleValueStats::Clear();
  clear_has_direction_x_stats();
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::direction_x_stats() const {
  return direction_x_stats_ != NULL ? *direction_x_stats_ : *default_instance_->direction_x_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_direction_x_stats() {
  set_has_direction_x_stats();
  if (direction_x_stats_ == NULL) direction_x_stats_ = new ::mozc::usage_stats::Stats_DoubleValueStats;
  return direction_x_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_direction_x_stats() {
  clear_has_direction_x_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = direction_x_stats_;
  direction_x_stats_ = NULL;
  return temp;
}
inline void Stats_TouchEventStats::set_allocated_direction_x_stats(::mozc::usage_stats::Stats_DoubleValueStats* direction_x_stats) {
  delete direction_x_stats_;
  direction_x_stats_ = direction_x_stats;
  if (direction_x_stats) {
    set_has_direction_x_stats();
  } else {
    clear_has_direction_x_stats();
  }
}

// optional .mozc.usage_stats.Stats.DoubleValueStats direction_y_stats = 5;
inline bool Stats_TouchEventStats::has_direction_y_stats() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Stats_TouchEventStats::set_has_direction_y_stats() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Stats_TouchEventStats::clear_has_direction_y_stats() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Stats_TouchEventStats::clear_direction_y_stats() {
  if (direction_y_stats_ != NULL) direction_y_stats_->::mozc::usage_stats::Stats_DoubleValueStats::Clear();
  clear_has_direction_y_stats();
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::direction_y_stats() const {
  return direction_y_stats_ != NULL ? *direction_y_stats_ : *default_instance_->direction_y_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_direction_y_stats() {
  set_has_direction_y_stats();
  if (direction_y_stats_ == NULL) direction_y_stats_ = new ::mozc::usage_stats::Stats_DoubleValueStats;
  return direction_y_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_direction_y_stats() {
  clear_has_direction_y_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = direction_y_stats_;
  direction_y_stats_ = NULL;
  return temp;
}
inline void Stats_TouchEventStats::set_allocated_direction_y_stats(::mozc::usage_stats::Stats_DoubleValueStats* direction_y_stats) {
  delete direction_y_stats_;
  direction_y_stats_ = direction_y_stats;
  if (direction_y_stats) {
    set_has_direction_y_stats();
  } else {
    clear_has_direction_y_stats();
  }
}

// optional .mozc.usage_stats.Stats.DoubleValueStats time_length_stats = 6;
inline bool Stats_TouchEventStats::has_time_length_stats() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Stats_TouchEventStats::set_has_time_length_stats() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Stats_TouchEventStats::clear_has_time_length_stats() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Stats_TouchEventStats::clear_time_length_stats() {
  if (time_length_stats_ != NULL) time_length_stats_->::mozc::usage_stats::Stats_DoubleValueStats::Clear();
  clear_has_time_length_stats();
}
inline const ::mozc::usage_stats::Stats_DoubleValueStats& Stats_TouchEventStats::time_length_stats() const {
  return time_length_stats_ != NULL ? *time_length_stats_ : *default_instance_->time_length_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::mutable_time_length_stats() {
  set_has_time_length_stats();
  if (time_length_stats_ == NULL) time_length_stats_ = new ::mozc::usage_stats::Stats_DoubleValueStats;
  return time_length_stats_;
}
inline ::mozc::usage_stats::Stats_DoubleValueStats* Stats_TouchEventStats::release_time_length_stats() {
  clear_has_time_length_stats();
  ::mozc::usage_stats::Stats_DoubleValueStats* temp = time_length_stats_;
  time_length_stats_ = NULL;
  return temp;
}
inline void Stats_TouchEventStats::set_allocated_time_length_stats(::mozc::usage_stats::Stats_DoubleValueStats* time_length_stats) {
  delete time_length_stats_;
  time_length_stats_ = time_length_stats;
  if (time_length_stats) {
    set_has_time_length_stats();
  } else {
    clear_has_time_length_stats();
  }
}

// -------------------------------------------------------------------

// Stats_VirtualKeyboardStats

// optional string keyboard_name = 1;
inline bool Stats_VirtualKeyboardStats::has_keyboard_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stats_VirtualKeyboardStats::set_has_keyboard_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stats_VirtualKeyboardStats::clear_has_keyboard_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stats_VirtualKeyboardStats::clear_keyboard_name() {
  if (keyboard_name_ != &::google::protobuf::internal::kEmptyString) {
    keyboard_name_->clear();
  }
  clear_has_keyboard_name();
}
inline const ::std::string& Stats_VirtualKeyboardStats::keyboard_name() const {
  return *keyboard_name_;
}
inline void Stats_VirtualKeyboardStats::set_keyboard_name(const ::std::string& value) {
  set_has_keyboard_name();
  if (keyboard_name_ == &::google::protobuf::internal::kEmptyString) {
    keyboard_name_ = new ::std::string;
  }
  keyboard_name_->assign(value);
}
inline void Stats_VirtualKeyboardStats::set_keyboard_name(const char* value) {
  set_has_keyboard_name();
  if (keyboard_name_ == &::google::protobuf::internal::kEmptyString) {
    keyboard_name_ = new ::std::string;
  }
  keyboard_name_->assign(value);
}
inline void Stats_VirtualKeyboardStats::set_keyboard_name(const char* value, size_t size) {
  set_has_keyboard_name();
  if (keyboard_name_ == &::google::protobuf::internal::kEmptyString) {
    keyboard_name_ = new ::std::string;
  }
  keyboard_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Stats_VirtualKeyboardStats::mutable_keyboard_name() {
  set_has_keyboard_name();
  if (keyboard_name_ == &::google::protobuf::internal::kEmptyString) {
    keyboard_name_ = new ::std::string;
  }
  return keyboard_name_;
}
inline ::std::string* Stats_VirtualKeyboardStats::release_keyboard_name() {
  clear_has_keyboard_name();
  if (keyboard_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = keyboard_name_;
    keyboard_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Stats_VirtualKeyboardStats::set_allocated_keyboard_name(::std::string* keyboard_name) {
  if (keyboard_name_ != &::google::protobuf::internal::kEmptyString) {
    delete keyboard_name_;
  }
  if (keyboard_name) {
    set_has_keyboard_name();
    keyboard_name_ = keyboard_name;
  } else {
    clear_has_keyboard_name();
    keyboard_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .mozc.usage_stats.Stats.TouchEventStats touch_event_stats = 2;
inline int Stats_VirtualKeyboardStats::touch_event_stats_size() const {
  return touch_event_stats_.size();
}
inline void Stats_VirtualKeyboardStats::clear_touch_event_stats() {
  touch_event_stats_.Clear();
}
inline const ::mozc::usage_stats::Stats_TouchEventStats& Stats_VirtualKeyboardStats::touch_event_stats(int index) const {
  return touch_event_stats_.Get(index);
}
inline ::mozc::usage_stats::Stats_TouchEventStats* Stats_VirtualKeyboardStats::mutable_touch_event_stats(int index) {
  return touch_event_stats_.Mutable(index);
}
inline ::mozc::usage_stats::Stats_TouchEventStats* Stats_VirtualKeyboardStats::add_touch_event_stats() {
  return touch_event_stats_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_TouchEventStats >&
Stats_VirtualKeyboardStats::touch_event_stats() const {
  return touch_event_stats_;
}
inline ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_TouchEventStats >*
Stats_VirtualKeyboardStats::mutable_touch_event_stats() {
  return &touch_event_stats_;
}

// -------------------------------------------------------------------

// Stats

// required string name = 1;
inline bool Stats::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Stats::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Stats::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Stats::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Stats::name() const {
  return *name_;
}
inline void Stats::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Stats::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Stats::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Stats::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Stats::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Stats::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// required .mozc.usage_stats.Stats.Type type = 2;
inline bool Stats::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Stats::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Stats::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Stats::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::mozc::usage_stats::Stats_Type Stats::type() const {
  return static_cast< ::mozc::usage_stats::Stats_Type >(type_);
}
inline void Stats::set_type(::mozc::usage_stats::Stats_Type value) {
  assert(::mozc::usage_stats::Stats_Type_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional uint32 count = 3;
inline bool Stats::has_count() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Stats::set_has_count() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Stats::clear_has_count() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Stats::clear_count() {
  count_ = 0u;
  clear_has_count();
}
inline ::google::protobuf::uint32 Stats::count() const {
  return count_;
}
inline void Stats::set_count(::google::protobuf::uint32 value) {
  set_has_count();
  count_ = value;
}

// optional uint64 total_time = 10;
inline bool Stats::has_total_time() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Stats::set_has_total_time() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Stats::clear_has_total_time() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Stats::clear_total_time() {
  total_time_ = GOOGLE_ULONGLONG(0);
  clear_has_total_time();
}
inline ::google::protobuf::uint64 Stats::total_time() const {
  return total_time_;
}
inline void Stats::set_total_time(::google::protobuf::uint64 value) {
  set_has_total_time();
  total_time_ = value;
}

// optional uint32 num_timings = 4;
inline bool Stats::has_num_timings() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Stats::set_has_num_timings() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Stats::clear_has_num_timings() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Stats::clear_num_timings() {
  num_timings_ = 0u;
  clear_has_num_timings();
}
inline ::google::protobuf::uint32 Stats::num_timings() const {
  return num_timings_;
}
inline void Stats::set_num_timings(::google::protobuf::uint32 value) {
  set_has_num_timings();
  num_timings_ = value;
}

// optional uint32 avg_time = 5;
inline bool Stats::has_avg_time() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Stats::set_has_avg_time() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Stats::clear_has_avg_time() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Stats::clear_avg_time() {
  avg_time_ = 0u;
  clear_has_avg_time();
}
inline ::google::protobuf::uint32 Stats::avg_time() const {
  return avg_time_;
}
inline void Stats::set_avg_time(::google::protobuf::uint32 value) {
  set_has_avg_time();
  avg_time_ = value;
}

// optional uint32 min_time = 6;
inline bool Stats::has_min_time() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Stats::set_has_min_time() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Stats::clear_has_min_time() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Stats::clear_min_time() {
  min_time_ = 0u;
  clear_has_min_time();
}
inline ::google::protobuf::uint32 Stats::min_time() const {
  return min_time_;
}
inline void Stats::set_min_time(::google::protobuf::uint32 value) {
  set_has_min_time();
  min_time_ = value;
}

// optional uint32 max_time = 7;
inline bool Stats::has_max_time() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Stats::set_has_max_time() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Stats::clear_has_max_time() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Stats::clear_max_time() {
  max_time_ = 0u;
  clear_has_max_time();
}
inline ::google::protobuf::uint32 Stats::max_time() const {
  return max_time_;
}
inline void Stats::set_max_time(::google::protobuf::uint32 value) {
  set_has_max_time();
  max_time_ = value;
}

// optional int32 int_value = 8;
inline bool Stats::has_int_value() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Stats::set_has_int_value() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Stats::clear_has_int_value() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Stats::clear_int_value() {
  int_value_ = 0;
  clear_has_int_value();
}
inline ::google::protobuf::int32 Stats::int_value() const {
  return int_value_;
}
inline void Stats::set_int_value(::google::protobuf::int32 value) {
  set_has_int_value();
  int_value_ = value;
}

// optional bool boolean_value = 9;
inline bool Stats::has_boolean_value() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void Stats::set_has_boolean_value() {
  _has_bits_[0] |= 0x00000200u;
}
inline void Stats::clear_has_boolean_value() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void Stats::clear_boolean_value() {
  boolean_value_ = false;
  clear_has_boolean_value();
}
inline bool Stats::boolean_value() const {
  return boolean_value_;
}
inline void Stats::set_boolean_value(bool value) {
  set_has_boolean_value();
  boolean_value_ = value;
}

// repeated .mozc.usage_stats.Stats.VirtualKeyboardStats virtual_keyboard_stats = 11;
inline int Stats::virtual_keyboard_stats_size() const {
  return virtual_keyboard_stats_.size();
}
inline void Stats::clear_virtual_keyboard_stats() {
  virtual_keyboard_stats_.Clear();
}
inline const ::mozc::usage_stats::Stats_VirtualKeyboardStats& Stats::virtual_keyboard_stats(int index) const {
  return virtual_keyboard_stats_.Get(index);
}
inline ::mozc::usage_stats::Stats_VirtualKeyboardStats* Stats::mutable_virtual_keyboard_stats(int index) {
  return virtual_keyboard_stats_.Mutable(index);
}
inline ::mozc::usage_stats::Stats_VirtualKeyboardStats* Stats::add_virtual_keyboard_stats() {
  return virtual_keyboard_stats_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_VirtualKeyboardStats >&
Stats::virtual_keyboard_stats() const {
  return virtual_keyboard_stats_;
}
inline ::google::protobuf::RepeatedPtrField< ::mozc::usage_stats::Stats_VirtualKeyboardStats >*
Stats::mutable_virtual_keyboard_stats() {
  return &virtual_keyboard_stats_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace usage_stats
}  // namespace mozc

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::mozc::usage_stats::Stats_Type>() {
  return ::mozc::usage_stats::Stats_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_usage_5fstats_2fusage_5fstats_2eproto__INCLUDED
