// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session/state.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "session/state.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace mozc {
namespace session {

namespace {

const ::google::protobuf::Descriptor* SessionState_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  SessionState_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_session_2fstate_2eproto() {
  protobuf_AddDesc_session_2fstate_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "session/state.proto");
  GOOGLE_CHECK(file != NULL);
  SessionState_descriptor_ = file->message_type(0);
  static const int SessionState_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, created_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, committed_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, start_preedit_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, start_conversion_window_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, start_prediction_window_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, start_suggestion_window_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, start_infolist_window_time_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, preedit_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, candidates_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, request_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, input_field_type_),
  };
  SessionState_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      SessionState_descriptor_,
      SessionState::default_instance_,
      SessionState_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SessionState, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(SessionState));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_session_2fstate_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    SessionState_descriptor_, &SessionState::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_session_2fstate_2eproto() {
  delete SessionState::default_instance_;
  delete SessionState_reflection_;
}

void protobuf_AddDesc_session_2fstate_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::mozc::commands::protobuf_AddDesc_session_2fcandidates_2eproto();
  ::mozc::commands::protobuf_AddDesc_session_2fcommands_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023session/state.proto\022\014mozc.session\032\030ses"
    "sion/candidates.proto\032\026session/commands."
    "proto\"\345\003\n\014SessionState\022\n\n\002id\030\001 \002(\004\022\024\n\014cr"
    "eated_time\030\002 \001(\004\022\030\n\tcommitted\030\003 \001(\010:\005fal"
    "se\022\032\n\022start_preedit_time\030\n \001(\004\022$\n\034start_"
    "conversion_window_time\030\013 \001(\004\022$\n\034start_pr"
    "ediction_window_time\030\014 \001(\004\022$\n\034start_sugg"
    "estion_window_time\030\r \001(\004\022\"\n\032start_infoli"
    "st_window_time\030\016 \001(\004\022\'\n\007preedit\030\024 \001(\0132\026."
    "mozc.commands.Preedit\022-\n\ncandidates\030\025 \001("
    "\0132\031.mozc.commands.Candidates\022%\n\006result\030\027"
    " \001(\0132\025.mozc.commands.Result\022\'\n\007request\030\030"
    " \001(\0132\026.mozc.commands.Request\022\?\n\020input_fi"
    "eld_type\030\031 \001(\0162%.mozc.commands.Context.I"
    "nputFieldType", 573);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "session/state.proto", &protobuf_RegisterTypes);
  SessionState::default_instance_ = new SessionState();
  SessionState::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_session_2fstate_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_session_2fstate_2eproto {
  StaticDescriptorInitializer_session_2fstate_2eproto() {
    protobuf_AddDesc_session_2fstate_2eproto();
  }
} static_descriptor_initializer_session_2fstate_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int SessionState::kIdFieldNumber;
const int SessionState::kCreatedTimeFieldNumber;
const int SessionState::kCommittedFieldNumber;
const int SessionState::kStartPreeditTimeFieldNumber;
const int SessionState::kStartConversionWindowTimeFieldNumber;
const int SessionState::kStartPredictionWindowTimeFieldNumber;
const int SessionState::kStartSuggestionWindowTimeFieldNumber;
const int SessionState::kStartInfolistWindowTimeFieldNumber;
const int SessionState::kPreeditFieldNumber;
const int SessionState::kCandidatesFieldNumber;
const int SessionState::kResultFieldNumber;
const int SessionState::kRequestFieldNumber;
const int SessionState::kInputFieldTypeFieldNumber;
#endif  // !_MSC_VER

SessionState::SessionState()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void SessionState::InitAsDefaultInstance() {
  preedit_ = const_cast< ::mozc::commands::Preedit*>(&::mozc::commands::Preedit::default_instance());
  candidates_ = const_cast< ::mozc::commands::Candidates*>(&::mozc::commands::Candidates::default_instance());
  result_ = const_cast< ::mozc::commands::Result*>(&::mozc::commands::Result::default_instance());
  request_ = const_cast< ::mozc::commands::Request*>(&::mozc::commands::Request::default_instance());
}

SessionState::SessionState(const SessionState& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void SessionState::SharedCtor() {
  _cached_size_ = 0;
  id_ = GOOGLE_ULONGLONG(0);
  created_time_ = GOOGLE_ULONGLONG(0);
  committed_ = false;
  start_preedit_time_ = GOOGLE_ULONGLONG(0);
  start_conversion_window_time_ = GOOGLE_ULONGLONG(0);
  start_prediction_window_time_ = GOOGLE_ULONGLONG(0);
  start_suggestion_window_time_ = GOOGLE_ULONGLONG(0);
  start_infolist_window_time_ = GOOGLE_ULONGLONG(0);
  preedit_ = NULL;
  candidates_ = NULL;
  result_ = NULL;
  request_ = NULL;
  input_field_type_ = 1;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

SessionState::~SessionState() {
  SharedDtor();
}

void SessionState::SharedDtor() {
  if (this != default_instance_) {
    delete preedit_;
    delete candidates_;
    delete result_;
    delete request_;
  }
}

void SessionState::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SessionState::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return SessionState_descriptor_;
}

const SessionState& SessionState::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_session_2fstate_2eproto();
  return *default_instance_;
}

SessionState* SessionState::default_instance_ = NULL;

SessionState* SessionState::New() const {
  return new SessionState;
}

void SessionState::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    id_ = GOOGLE_ULONGLONG(0);
    created_time_ = GOOGLE_ULONGLONG(0);
    committed_ = false;
    start_preedit_time_ = GOOGLE_ULONGLONG(0);
    start_conversion_window_time_ = GOOGLE_ULONGLONG(0);
    start_prediction_window_time_ = GOOGLE_ULONGLONG(0);
    start_suggestion_window_time_ = GOOGLE_ULONGLONG(0);
    start_infolist_window_time_ = GOOGLE_ULONGLONG(0);
  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (has_preedit()) {
      if (preedit_ != NULL) preedit_->::mozc::commands::Preedit::Clear();
    }
    if (has_candidates()) {
      if (candidates_ != NULL) candidates_->::mozc::commands::Candidates::Clear();
    }
    if (has_result()) {
      if (result_ != NULL) result_->::mozc::commands::Result::Clear();
    }
    if (has_request()) {
      if (request_ != NULL) request_->::mozc::commands::Request::Clear();
    }
    input_field_type_ = 1;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool SessionState::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint64 id = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(16)) goto parse_created_time;
        break;
      }

      // optional uint64 created_time = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_created_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &created_time_)));
          set_has_created_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(24)) goto parse_committed;
        break;
      }

      // optional bool committed = 3 [default = false];
      case 3: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_committed:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &committed_)));
          set_has_committed();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(80)) goto parse_start_preedit_time;
        break;
      }

      // optional uint64 start_preedit_time = 10;
      case 10: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_start_preedit_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_preedit_time_)));
          set_has_start_preedit_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(88)) goto parse_start_conversion_window_time;
        break;
      }

      // optional uint64 start_conversion_window_time = 11;
      case 11: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_start_conversion_window_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_conversion_window_time_)));
          set_has_start_conversion_window_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(96)) goto parse_start_prediction_window_time;
        break;
      }

      // optional uint64 start_prediction_window_time = 12;
      case 12: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_start_prediction_window_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_prediction_window_time_)));
          set_has_start_prediction_window_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(104)) goto parse_start_suggestion_window_time;
        break;
      }

      // optional uint64 start_suggestion_window_time = 13;
      case 13: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_start_suggestion_window_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_suggestion_window_time_)));
          set_has_start_suggestion_window_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(112)) goto parse_start_infolist_window_time;
        break;
      }

      // optional uint64 start_infolist_window_time = 14;
      case 14: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_start_infolist_window_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &start_infolist_window_time_)));
          set_has_start_infolist_window_time();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(162)) goto parse_preedit;
        break;
      }

      // optional .mozc.commands.Preedit preedit = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_preedit:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_preedit()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(170)) goto parse_candidates;
        break;
      }

      // optional .mozc.commands.Candidates candidates = 21;
      case 21: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_candidates:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_candidates()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(186)) goto parse_result;
        break;
      }

      // optional .mozc.commands.Result result = 23;
      case 23: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_result:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_result()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(194)) goto parse_request;
        break;
      }

      // optional .mozc.commands.Request request = 24;
      case 24: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_request:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_request()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(200)) goto parse_input_field_type;
        break;
      }

      // optional .mozc.commands.Context.InputFieldType input_field_type = 25;
      case 25: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
         parse_input_field_type:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::mozc::commands::Context_InputFieldType_IsValid(value)) {
            set_input_field_type(static_cast< ::mozc::commands::Context_InputFieldType >(value));
          } else {
            mutable_unknown_fields()->AddVarint(25, value);
          }
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void SessionState::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required uint64 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(1, this->id(), output);
  }

  // optional uint64 created_time = 2;
  if (has_created_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(2, this->created_time(), output);
  }

  // optional bool committed = 3 [default = false];
  if (has_committed()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->committed(), output);
  }

  // optional uint64 start_preedit_time = 10;
  if (has_start_preedit_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(10, this->start_preedit_time(), output);
  }

  // optional uint64 start_conversion_window_time = 11;
  if (has_start_conversion_window_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(11, this->start_conversion_window_time(), output);
  }

  // optional uint64 start_prediction_window_time = 12;
  if (has_start_prediction_window_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(12, this->start_prediction_window_time(), output);
  }

  // optional uint64 start_suggestion_window_time = 13;
  if (has_start_suggestion_window_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(13, this->start_suggestion_window_time(), output);
  }

  // optional uint64 start_infolist_window_time = 14;
  if (has_start_infolist_window_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(14, this->start_infolist_window_time(), output);
  }

  // optional .mozc.commands.Preedit preedit = 20;
  if (has_preedit()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20, this->preedit(), output);
  }

  // optional .mozc.commands.Candidates candidates = 21;
  if (has_candidates()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      21, this->candidates(), output);
  }

  // optional .mozc.commands.Result result = 23;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      23, this->result(), output);
  }

  // optional .mozc.commands.Request request = 24;
  if (has_request()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      24, this->request(), output);
  }

  // optional .mozc.commands.Context.InputFieldType input_field_type = 25;
  if (has_input_field_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      25, this->input_field_type(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* SessionState::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required uint64 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(1, this->id(), target);
  }

  // optional uint64 created_time = 2;
  if (has_created_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(2, this->created_time(), target);
  }

  // optional bool committed = 3 [default = false];
  if (has_committed()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->committed(), target);
  }

  // optional uint64 start_preedit_time = 10;
  if (has_start_preedit_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(10, this->start_preedit_time(), target);
  }

  // optional uint64 start_conversion_window_time = 11;
  if (has_start_conversion_window_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(11, this->start_conversion_window_time(), target);
  }

  // optional uint64 start_prediction_window_time = 12;
  if (has_start_prediction_window_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(12, this->start_prediction_window_time(), target);
  }

  // optional uint64 start_suggestion_window_time = 13;
  if (has_start_suggestion_window_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(13, this->start_suggestion_window_time(), target);
  }

  // optional uint64 start_infolist_window_time = 14;
  if (has_start_infolist_window_time()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(14, this->start_infolist_window_time(), target);
  }

  // optional .mozc.commands.Preedit preedit = 20;
  if (has_preedit()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        20, this->preedit(), target);
  }

  // optional .mozc.commands.Candidates candidates = 21;
  if (has_candidates()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        21, this->candidates(), target);
  }

  // optional .mozc.commands.Result result = 23;
  if (has_result()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        23, this->result(), target);
  }

  // optional .mozc.commands.Request request = 24;
  if (has_request()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        24, this->request(), target);
  }

  // optional .mozc.commands.Context.InputFieldType input_field_type = 25;
  if (has_input_field_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      25, this->input_field_type(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int SessionState::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required uint64 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->id());
    }

    // optional uint64 created_time = 2;
    if (has_created_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->created_time());
    }

    // optional bool committed = 3 [default = false];
    if (has_committed()) {
      total_size += 1 + 1;
    }

    // optional uint64 start_preedit_time = 10;
    if (has_start_preedit_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->start_preedit_time());
    }

    // optional uint64 start_conversion_window_time = 11;
    if (has_start_conversion_window_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->start_conversion_window_time());
    }

    // optional uint64 start_prediction_window_time = 12;
    if (has_start_prediction_window_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->start_prediction_window_time());
    }

    // optional uint64 start_suggestion_window_time = 13;
    if (has_start_suggestion_window_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->start_suggestion_window_time());
    }

    // optional uint64 start_infolist_window_time = 14;
    if (has_start_infolist_window_time()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt64Size(
          this->start_infolist_window_time());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional .mozc.commands.Preedit preedit = 20;
    if (has_preedit()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->preedit());
    }

    // optional .mozc.commands.Candidates candidates = 21;
    if (has_candidates()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->candidates());
    }

    // optional .mozc.commands.Result result = 23;
    if (has_result()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->result());
    }

    // optional .mozc.commands.Request request = 24;
    if (has_request()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->request());
    }

    // optional .mozc.commands.Context.InputFieldType input_field_type = 25;
    if (has_input_field_type()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->input_field_type());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SessionState::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const SessionState* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const SessionState*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void SessionState::MergeFrom(const SessionState& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_created_time()) {
      set_created_time(from.created_time());
    }
    if (from.has_committed()) {
      set_committed(from.committed());
    }
    if (from.has_start_preedit_time()) {
      set_start_preedit_time(from.start_preedit_time());
    }
    if (from.has_start_conversion_window_time()) {
      set_start_conversion_window_time(from.start_conversion_window_time());
    }
    if (from.has_start_prediction_window_time()) {
      set_start_prediction_window_time(from.start_prediction_window_time());
    }
    if (from.has_start_suggestion_window_time()) {
      set_start_suggestion_window_time(from.start_suggestion_window_time());
    }
    if (from.has_start_infolist_window_time()) {
      set_start_infolist_window_time(from.start_infolist_window_time());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_preedit()) {
      mutable_preedit()->::mozc::commands::Preedit::MergeFrom(from.preedit());
    }
    if (from.has_candidates()) {
      mutable_candidates()->::mozc::commands::Candidates::MergeFrom(from.candidates());
    }
    if (from.has_result()) {
      mutable_result()->::mozc::commands::Result::MergeFrom(from.result());
    }
    if (from.has_request()) {
      mutable_request()->::mozc::commands::Request::MergeFrom(from.request());
    }
    if (from.has_input_field_type()) {
      set_input_field_type(from.input_field_type());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void SessionState::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SessionState::CopyFrom(const SessionState& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SessionState::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_preedit()) {
    if (!this->preedit().IsInitialized()) return false;
  }
  if (has_candidates()) {
    if (!this->candidates().IsInitialized()) return false;
  }
  if (has_result()) {
    if (!this->result().IsInitialized()) return false;
  }
  return true;
}

void SessionState::Swap(SessionState* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(created_time_, other->created_time_);
    std::swap(committed_, other->committed_);
    std::swap(start_preedit_time_, other->start_preedit_time_);
    std::swap(start_conversion_window_time_, other->start_conversion_window_time_);
    std::swap(start_prediction_window_time_, other->start_prediction_window_time_);
    std::swap(start_suggestion_window_time_, other->start_suggestion_window_time_);
    std::swap(start_infolist_window_time_, other->start_infolist_window_time_);
    std::swap(preedit_, other->preedit_);
    std::swap(candidates_, other->candidates_);
    std::swap(result_, other->result_);
    std::swap(request_, other->request_);
    std::swap(input_field_type_, other->input_field_type_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata SessionState::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = SessionState_descriptor_;
  metadata.reflection = SessionState_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace session
}  // namespace mozc

// @@protoc_insertion_point(global_scope)
