// This header file is generated by gen_existence_data.
namespace CollocationSuppressionData{
const char kExistenceFilter_data[] =
"\x28\x00\x00\x00\x01\x00\x00\x00\x07\x00\x00\x00\x04\x00\x42\x08\x20\x00\x00\x00"
;
const size_t kExistenceFilter_size = 20;
}  // namespace CollocationSuppressionData
