// This header file is generated by gen_existence_data.
namespace CollocationData{
const char kExistenceFilter_data[] =
"\x48\x00\x00\x00\x02\x00\x00\x00\x07\x00\x00\x00\x0B\x80\x08\x90\x00\x28\x43\x20"
"\x20\x00\x00\x00"
;
const size_t kExistenceFilter_size = 24;
}  // namespace CollocationData
